sudo: false

os:
- linux
- osx

language: d

d:
- dmd-2.084.1
- dmd-2.083.1
- dmd-2.082.1

env:
  global:
  - LATEST=2.084.1

  matrix:
  - ARCH=x86_64
  - ARCH=x86

matrix:
  include:
  - name: D-Scanner
    d: dmd-$LATEST
    env: DSCANNER=0.5.11
    os: linux
  - name: DDoc
    d: dmd-$LATEST
    env: DDOC=true
    os: linux
  allow_failures:
  - name: D-Scanner
    d: dmd-$LATEST
    env: DSCANNER=0.5.11
    os: linux

addons:
  apt:
    packages:
    - gcc-multilib

before_script:
- if [ "`$DC --version | head -n 1 | grep v$LATEST`" ] &&
     [ -z "$DSCANNER$DDOC" ]; then
    export UNITTEST="unittest-cov";
  fi

script:
- if [ -n "$DDOC" ]; then
    dub build -b ddox --compiler=$DC;
  elif [ -z "$DSCANNER" ]; then
    dub test -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC;
  else
    dub fetch dscanner --version=$DSCANNER;

    FILES=$(find source -type f);
    dub run dscanner -- --styleCheck $FILES;
  fi

after_success:
- test "$UNITTEST" && bash <(curl -s https://codecov.io/bash)
