sudo: false

os:
- linux
- osx

language: d

d:
- dmd-2.082.0
- dmd-2.081.2

env:
  matrix:
  - ARCH=x86_64
  - ARCH=x86

matrix:
  include:
  - name: "D-Scanner"
    d: dmd-2.082.0
    env: DSCANNER=0.5.10
    os: linux

addons:
  apt:
    packages:
    - gcc-multilib

before_script:
- if [ "`$DC --version | head -n 1 | grep 'v2.082.0'`" ] &&
     [ -z "$DSCANNER" ]; then
    export UNITTEST="unittest-cov";
  fi

script:
- if [ -z "$DSCANNER" ]; then
    dub test -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC;
  else
    dub fetch dscanner --version=$DSCANNER;

    FILES=$(find source -type f);
    dub run dscanner -- --styleCheck $FILES;
  fi

after_success:
- test "$UNITTEST" && bash <(curl -s https://codecov.io/bash)
