sudo: false

os:
  - linux
  - osx

language: d

d:
  - dmd-2.074.1
  - dmd-2.073.2
  - dmd-2.072.2
  - dmd-2.071.2

env: 
  matrix:
    - ARCH=x86_64
    - ARCH=x86

addons:
  apt:
    packages:
      - gcc-multilib

before_script:
  - if [ "$PS1" = '(dmd-2.074.1)' ]; then
      export UNITTEST="unittest-cov";
    fi

script:
  - dub test -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC
  - if [ "$UNITTEST" = "unittest-cov" -a "$ARCH" = "x86_64" -a "$TRAVIS_OS_NAME" = "linux" ]; then
      dub fetch dscanner && dub run dscanner -- -Isource --styleCheck;
    fi

after_success:
  - test "$UNITTEST" = "unittest-cov" && bash <(curl -s https://codecov.io/bash)
