sudo: false

os:
- linux
- osx

language: d

d:
- dmd-2.085.0
- dmd-2.084.1
- dmd-2.082.1

env:
  global:
  - LATEST=2.085.0

  matrix:
  - ARCH=x86_64
  - ARCH=x86

matrix:
  include:
  - name: D-Scanner
    d: dmd-$LATEST
    env: DSCANNER=0.7.0
    os: linux
  - name: DDoc
    d: dmd-$LATEST
    env: DDOC=true
    os: linux

addons:
  apt:
    packages:
    - gcc-multilib

before_script:
- if [ "`$DC --version | head -n 1 | grep v$LATEST`" ] &&
     [ -z "$DSCANNER$DDOC" ]; then
    export UNITTEST="unittest-cov";
  fi

script:
- set -e;
  if [ -n "$DDOC" ]; then
    dub build :meta -b ddox --compiler=$DC;
    dub build :sys -b ddox --compiler=$DC;
    dub build :os -b ddox --compiler=$DC;
    dub build :encoding -b ddox --compiler=$DC;
    dub build :middle -b ddox --compiler=$DC;
    dub build :test -b ddox --compiler=$DC;
    dub build -b ddox --compiler=$DC;
  elif [ -z "$DSCANNER" ]; then
    dub test :meta -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC;
    dub test :sys -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC;
    dub test :os -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC;
    dub test :encoding -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC;
    dub test :middle -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC;
    dub test :test -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC;
    dub test -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC;
  else
    dub fetch dscanner --version=$DSCANNER;

    FILES=$(find */tanya -type f);
    dub run dscanner -- --styleCheck $FILES;
  fi

after_success:
- test "$UNITTEST" && bash <(curl -s https://codecov.io/bash) || true
