sudo: false

os:
  - linux
  - osx

language: d

d:
  - dmd-2.079.1
  - dmd-2.078.3
  - dmd-2.077.1

env:
  matrix:
    - ARCH=x86_64
    - ARCH=x86

addons:
  apt:
    packages:
      - gcc-multilib

before_script:
  - if [ "`$DC --version | head -n 1 | grep 'v2.079.1'`" ]; then
      export UNITTEST="unittest-cov";
    fi

script:
  - dub test -b ${UNITTEST:-unittest} --arch=$ARCH --compiler=$DC
  - if [ "$UNITTEST" ] && [ "$ARCH" = "x86_64" ] && [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      dub fetch dscanner;
      dub run dscanner -- --styleCheck ./source/;
    fi

after_success:
  - test "$UNITTEST" && bash <(curl -s https://codecov.io/bash)
