platform: x64
os: Visual Studio 2015

environment:
  matrix:
    - DC: dmd
      DVersion: 2.085.0
      arch: x64
    - DC: dmd
      DVersion: 2.085.0
      arch: x86
    - DC: dmd
      DVersion: 2.082.1
      arch: x64
    - DC: dmd
      DVersion: 2.082.1
      arch: x86

skip_tags: true

install:
  - ps: function SetUpDCompiler
        {
          $env:toolchain = "msvc";
          $version = $env:DVersion;
          Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
          echo "finished.";
          pushd c:\\;
          7z x dmd.7z > $null;
          popd;
        }
  - ps: SetUpDCompiler

before_build:
  - ps: if($env:arch -eq "x86"){
          $env:compilersetupargs = "x86";
          $env:Darch = "x86_mscoff";
        }
        elseif($env:arch -eq "x64"){
          $env:compilersetupargs = "amd64";
          $env:Darch = "x86_64";
        }
  - ps: $env:PATH += ";C:\dmd2\windows\bin;";
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" %compilersetupargs%

build_script:
  - echo dummy build script - dont remove me

test_script:
  - echo %Darch%
  - echo %PATH%
  - 'dub --version'
  - '%DC% --version'
  - dub test :meta -b unittest --arch=%Darch% --compiler=%DC%
  - dub test :sys -b unittest --arch=%Darch% --compiler=%DC%
  - dub test :os -b unittest --arch=%Darch% --compiler=%DC%
  - dub test :encoding -b unittest --arch=%Darch% --compiler=%DC%
  - dub test :middle -b unittest --arch=%Darch% --compiler=%DC%
  - dub test :test -b unittest --arch=%Darch% --compiler=%DC%
  - dub test -b unittest --arch=%Darch% --compiler=%DC%
