platform: x64
os: Visual Studio 2017

environment:
 matrix:
  - DC: dmd
    DVersion: 2.074.0
    arch: x64
  - DC: dmd
    DVersion: 2.074.0
    arch: x86
  - DC: dmd
    DVersion: 2.073.2
    arch: x64
  - DC: dmd
    DVersion: 2.073.2
    arch: x86
  - DC: dmd
    DVersion: 2.072.2
    arch: x64
  - DC: dmd
    DVersion: 2.072.2
    arch: x86
  - DC: dmd
    DVersion: 2.071.2
    arch: x64
  - DC: dmd
    DVersion: 2.071.2
    arch: x86

skip_tags: true

install:
  - ps: function SetUpDCompiler
        {
            $env:toolchain = "msvc";
            $version = $env:DVersion;
            Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
            echo "finished.";
            pushd c:\\;
            7z x dmd.7z > $null;
            popd;
        }
  - ps: SetUpDCompiler
  - powershell -Command Invoke-WebRequest http://code.dlang.org/files/dub-1.0.0-windows-x86.zip -OutFile dub.zip
  - 7z x dub.zip -odub > nul
  - set PATH=%CD%\%binpath%;%CD%\dub;%PATH%
  - dub --version

before_build:
  - ps: if($env:arch -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
            $env:LINKCMD64 = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\amd64\bin\link.exe"
          }
        elseif($env:arch -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
        }
  - ps: $env:PATH += ";C:\dmd2\windows\bin;";
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat";
  - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC"
  - '"%compilersetup%" -arch=%compilersetupargs%'

build_script:
 - echo dummy build script - dont remove me

test_script:
 - echo %PLATFORM%
 - echo %Darch%
 - echo %DC%
 - echo %PATH%
 - '%DC% --version'
 - dub test --arch=%Darch% --compiler=%DC%
