platform: x64
os: Visual Studio 2017

environment:
 matrix:
  - DC: dmd
    DVersion: 2.074.0
    arch: x86
  - DC: dmd
    DVersion: 2.073.2
    arch: x86
  - DC: dmd
    DVersion: 2.072.2
    arch: x86
  - DC: dmd
    DVersion: 2.071.2
    arch: x86

skip_tags: true

install:
  - ps: function SetUpDCompiler
        {
            $env:toolchain = "msvc";
            $version = $env:DVersion;
            Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
            echo "finished.";
            pushd c:\\;
            7z x dmd.7z > $null;
            popd;
        }
  - ps: SetUpDCompiler

  - ps: if($env:DVersion -eq "2.071.2"){
            Invoke-WebRequest "http://code.dlang.org/files/dub-1.2.1-windows-x86.zip" -OutFile "dub.zip";
            7z x dub.zip -odub > $null;
            Move-Item "dub/dub.exe" "C:\dmd2\windows\bin"
          }

before_build:
  - ps: $env:PATH += ";C:\dmd2\windows\bin;";
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=%arch%

build_script:
 - echo dummy build script - dont remove me

test_script:
 - echo %DC%
 - echo %PATH%
 - 'dub --version'
 - '%DC% --version'
 - dub test --arch=x86 --compiler=%DC%
